app/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

#yapf: disable
urlpatterns = [
    path('', views.ProfileView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('users', views.UsersView.as_view(), name='users'),
    path('users/create-update', views.CreateUpdatUserView.as_view(), name="create_update_user"),
]

app/dashboard/urls.py
from django.urls import path

from . import views

# yapf: disable

app_name = "dashboard"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('delete/<str:model_name>/<str:instance_id>', views.DeleteModelView.as_view(), name='delete_model'),
    path('model_agnostic_image_upload/<str:model_name>/<str:model_id>/<str:field_name>', views.ModelAgnosticImageUploadView.as_view(), name='model_agnostic_image_upload'),
    path('crop-model-image/<str:model_name>/<str:model_id>/<str:field_name>', views.CropModelImageView.as_view(), name='crop_model_image'),
    path('tasks/<str:task_id>/stream-status', views.StreamTaskStatusView.as_view(), name='stream_task_status'),

    # Students
    path('students/', views.StudentsView.as_view(), name='students'),
    path('students/create-update', views.CreateUpdateStudentView.as_view(), name='create_update_student'),
    path('students/create-update-bulk', views.AddBulkStudents.as_view(), name='create_update_student_bulk'),

    # Subjects
    path('subjects/', views.SubjectsView.as_view(), name='subjects'),
    path('subjects/create-update', views.CreateUpdateSubjectView.as_view(), name="create_update_subject"),

    # Courses
    path('courses/', views.CoursesView.as_view(), name='courses'),
    path('courses/create-update', views.CreateUpdateCourseView.as_view(), name="create_update_course"),

    # Department
    path('departments/', views.DepartmentsView.as_view(), name='departments'),
    path('departments/create-update', views.CreateUpdateDepartmentView.as_view(), name="create_update_department"),

    # Staff
    path('staff/', views.StaffView.as_view(), name='staff'),
    path('staff/create-update', views.CreateUpdateStaffView.as_view(), name="create_update_staff"),

    # Staff
    path('classes/', views.ClassesView.as_view(), name='classes'),
    path('classes/create-update', views.CreateUpdateClassView.as_view(), name="create_update_class"),

    # House
    path('houses/', views.HousesView.as_view(), name='houses'),
    path('houses/create-update', views.CreateUpdateHouseView.as_view(), name="create_update_house"),

    # House
    path('tasks/', views.TasksView.as_view(), name='tasks'),
    path('tasks/create-update', views.CreateUpdateTaskView.as_view(), name="create_update_task"),
    path('tasks/task-send-notification', views.SendTaskNotification.as_view(), name="task_send_notification"),

    # Action Center
    path('action-center/', views.ActionCenterView.as_view(), name='action_center'),
    path('action-center/subject-mapping', views.SubjectMappingView.as_view(), name='subject_mapping'),
    path('action-center/reset-subject-mapping', views.ResetSubjectMappingView.as_view(), name='reset_subject_mapping'),
    path('action-center/student-promotion', views.StudentPromotionView.as_view(), name='student_promotion'),
    path('action-center/student-promotion-revert', views.RevertPromotionView.as_view(), name='student_promotion_revert'),
    path('action-center/academic-record-selection', views.AcademicRecordSelectionView.as_view(), name='academic_record_selection'),
    path('action-center/academic-record-data', views.AcademicRecordDataView.as_view(), name='academic_record_data'),
    path('action-center/reset-academic-record-data', views.ResetAcademicRecord.as_view(), name='reset_academic_record_data'),

    # Reporting
    path('reporting/index', views.ReportingIndexView.as_view(), name='reporting_index'),
    path('reporting/student-full-report', views.StudentFullReportView.as_view(), name='student_full_report'),
    path('reporting/generate-report-sheet', views.BulkAcademicRecordReportView.as_view(), name='gerate_bulk_student_report_sheet'),
    path('reporting/generate-report-sheet/<str:task_id>/<str:filename>/status', views.StudentReportGenerationStatusView.as_view(), name='bulk_report_sheet_generation_status'),

    # Class teacher reporting
    path('reporting/class-teacher-report-filter', views.ClassTeacherSessionReportFilterView.as_view(), name='class_teacher_report_filter'),
    path('reporting/class-teacher-report-data', views.ClassTeacherSessionReportDataView.as_view(), name='class_teacher_report_data'),

    # House master reporting
    path('reporting/house-master-report-filter', views.HouseMasterSessionReportFilterView.as_view(), name='house_master_report_filter'),
    path('reporting/house-master-report-data', views.HouseMasterSessionReportDataView.as_view(), name='house_master_report_data'),

    # House master reporting
    path('reporting/assistant-head-report-filter', views.AssistantHeadSessionReportFilterView.as_view(), name='assistant_head_report_filter'),
    path('reporting/assistant-head-report-data', views.AssistantHeadSessionReportDataView.as_view(), name='assistant_head_report_data'),

    # Notifications
    path('notifications/', views.NotificationIndexView.as_view(), name='notifications'),
    path('notifications/history', views.NotificationHistoryView.as_view(), name='notification_history'),
    path('notifications/compose-sms/', views.ComposeSMS.as_view(), name='compose_sms'),
    path('notifications/preview-sms/', views.PreviewSMS.as_view(), name='preview_sms'),
    path('notifications/send-pin-sms/', views.SendPINNotification.as_view(), name='send_pin_sms'),
    path('notifications/confirm-pin-notification/', views.ConfirmPINNotification.as_view(), name='confirm_pin_notification'),
    path('notifications/report-notifications/', views.SendReportNotification.as_view(), name='report_notifications'),
    path('notifications/bill-notifications/', views.SendBillNotification.as_view(), name='bill_notifications'),
    path('notifications/report-notification-confirmation/', views.ConfirmReportNotification.as_view(), name='report_notification_confirmation'),
    path('notifications/bill-notification-confirmation/', views.ConfirmBillNotification.as_view(), name='bill_notification_confirmation'),
]


urlpatterns += [
    path('accounting/', views.AccountingIndexView.as_view(), name='accounting'),
    path('accounting/invoices', views.InvoicesView.as_view(), name='invoices'),
    path('accounting/payments', views.PaymentsView.as_view(), name='payments'),
    path('accounting/create-update-payment/<str:student_id>/pay', views.CreateUpdatePayments.as_view(), name='create_update_payment'),
    path('accounting/create-update-invoice', views.CreateUpdateInvoiceView.as_view(), name='create_update_invoice'),
    path('accounting/invoice/<str:invoice_id>/create_update_invoice_item', views.CreateUpdateInvoiceItem.as_view(), name='create_update_invoice_item'),
    path('accounting/invoice/<str:invoice_id>/details', views.InvoiceDetailsView.as_view(), name='invoice_details'),
    
    path('accounting/generate-bill-sheet/<str:invoice_id>', views.BulkInvoiceGenerator.as_view(), name='gerate_bulk_student_bill_sheet'),
    path('accounting/generate-bill-sheet/<str:task_id>/<str:filename>/status', views.GeneralReportStatusView.as_view(), name='bulk_bill_sheet_generation_status'),
    
    path('accounting/student-invoices/<str:student_id>/', views.StudentInvoicesView.as_view(), name='student_invoices'),
    path('accounting/student-invoices/<str:student_id>/<str:invoice_id>', views.StudentInvoiceDetailView.as_view(), name='student_invoice_details'),
]

urlpatterns += [
    path('inventory/', views.InventoryIndexView.as_view(), name='inventory_index'),
    path('inventory/inventories', views.InventoriesView.as_view(), name='inventories'),
    path('inventory/inventories/create-update', views.CreateUpdateInventoryView.as_view(), name="create_update_inventory"),

    path('inventory/issuance', views.IssuanceView.as_view(), name='issuance'),
    path('inventory/issuance/create-update', views.CreateUpdateIssuanceView.as_view(), name="create_update_issuance"),
]

#Personal
urlpatterns += [
    path('personal/academic-record', views.PesonalAcademicRecord.as_view(), name='personal_academic_record'),
    path('personal/my-invoices', views.MyInvoicesView.as_view(), name='my_invoices'),
    path('personal/my-invoices/<str:invoice_id>/detail', views.MyInvoiceDetailView.as_view(), name='my_invoice_detail'),
    path('personal/payment-history', views.PersonalPaymentHistory.as_view(), name='payment_history'),
]

# User profile
urlpatterns += [
    path('user-profile', views.UserProfileIndexView.as_view(), name='user_profile'),
    path('user-profile/photo', views.UserProfilePhotoView.as_view(), name='user_profile_profile'),
]

app/lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('app/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('setup/', include('setup.urls')),
    path('pdf/', include('pdf_processor.urls')),
    path('api/v1/', include('graphql_api.urls')),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

# Customize django admin page.
admin.site.site_header = "LMS SYSTEM ADMINISTRATION"  # default: "Django Administration"
admin.site.index_title = "Site Administration"  # default: "Site Administration"
admin.site.site_title = 'LMS System site admin'  # default: "Django site admin"

app/accounts/models.py
import decimal
from random import sample

import geocoder
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models


class UserManger(BaseUserManager):
    """Define a model manager for User model"""

    def _create_user(self, username, password=None, **extra_fields):
        """Create and save a User with the given email and password."""
        if not username:
            raise ValueError('The given email must be set')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, password, **extra_fields)

    def create_superuser(self, username, password=None, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):

    def get_pin():
        return "".join(
            sample(list(map(str, [1, 2, 3, 4, 5, 6, 7, 8, 9, 0])), 4))

    username = models.CharField(max_length=30, unique=True)
    surname = models.CharField(max_length=30, null=True, blank=True)
    other_names = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=10,null=True,blank=True) #yapf: disable
    title = models.CharField(max_length=20,default="", blank=True) #yapf: disable
    photo = models.ImageField(upload_to='users', blank=True)
    signature = models.ImageField(upload_to='signatures',
                                  null=True,
                                  blank=True)
    gender = models.CharField(max_length=20, blank=True, null=True)
    temporal_pin = models.CharField(max_length=10, default=get_pin)
    dob = models.DateTimeField(null=True, blank=True)

    activated = models.BooleanField(default=False)
    last_login = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    changed_password = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)

    objects = UserManger()

    USERNAME_FIELD = 'username'

    class Meta:
        permissions = [
            ('reset_password', 'Can reset user password'),
        ]

    def model_name(self):
        return self.__class__.__name__.lower()

    def signature_url(self):
        if self.signature:
            return self.signature.url
        return ""

    def get_title(self):
        group = self.groups.first()
        if group: return group.name
        return "Staff"

    def get_photo_url(self):
        if self.photo:
            return self.photo.url
        return "/static/images/default_profile.jpg"

    def get_name(self):
        if self.surname and self.other_names:
            return f"{self.surname.title()} {self.other_names.title()}"
        return self.username.split('@')[0].upper()

    def save(self, *args, **kwargs):
        if self.gender:
            self.gender = self.gender.lower()
        if self.title:
            self.title = self.title.lower()
        return super().save(*args, **kwargs)


#yapf: disable
class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="account")
    available_balance = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    main_balance = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def balance(self):
        return self.main_balance

    @property
    def amount_payable(self):
        return self.main_balance * -1

    def reset_balance(self, amount):
        self.available_balance = decimal.Decimal(amount)
        self.main_balance = decimal.Decimal(amount)
        self.save()

    def credit_account(self, amount):
        self.available_balance += decimal.Decimal(amount)
        self.main_balance += decimal.Decimal(amount)
        self.save()

class ActivityLog(models.Model):
    username = models.CharField(max_length=100)
    action = models.TextField()
    ip = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return "%s %s" % (self.username, self.action)

    def get_latlng(self):
        return geocoder.ip(self.registration_ip).latlng

app/accounts/forms.py
from django import forms

from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = [
            "username",
            "surname",
            "other_names",
            "phone",
            "title",
            "photo",
            "gender",
        ]

app/accounts/templates/accounts/users/edit_user.html
{% extends 'templates/dashboard/base_template.html' %}
{% block page_title %}Users{% endblock %}
{% block active-sidebar-item-id %}users{%endblock%}

{% block breadcrumb %}
<section class="breadcrumb">
    <a href="{% url 'dashboard:index' %}" class="">Home <i class="bi bi-chevron-right"></i></a>
    <a href="{% url 'dashboard:courses' %}">Users <i class="bi bi-chevron-right"></i></a>
    <a class="active">{{user.get_name|title}}</a>
</section>
{% endblock %}

{% block content %}

<div class="row col-md-11 mx-auto">
    <section class="col-md-6 mx-auto">
        <div class="card p-4">
            <div class="d-flex justify-content-between">
                <h6>USER</h6>
            </div>
            {% include 'accounts/users/form_user.html' %}
        </div>
    </section>
</div>
{% endblock %}

app/accounts/templates/accounts/users/form_user.html
<form action="{% url 'accounts:create_update_user' %}" class="needs-validation my-4" method="POST" novalidate>
    {% csrf_token %}
    <input type="hidden" name="id" value="{{id}}">
    <div class="col-md-8 mx-auto">
        <div class="form-group my-3">
            <label for="name">Username</label>
            <input class="form-control" placeholder="Username" value="{{username}}" type="text" name="username"
                id="username" required>
            <div class="invalid-feedback">
                Please this field is required.
            </div>
        </div>

        <div class="form-group my-3">
            <label for="name">Surname</label>
            <input class="form-control" placeholder="Surname" value="{{surname}}" type="text" name="surname"
                id="surname" required>
            <div class="invalid-feedback">
                Please this field is required.
            </div>
        </div>

        <div class="form-group my-3">
            <label for="name">Other Names</label>
            <input class="form-control" placeholder="Other Names" value="{{other_names}}" type="text" name="other_names"
                id="other_names" required>
            <div class="invalid-feedback">
                Please this field is required.
            </div>
        </div>

        <div class="form-group my-3">
            <label for="name">Gender</label>
            <select name="gender" id="gender" class="form-select" required>
                <option value="">Choose gender</option>
                <option value="male" {% if gender == 'male' %}selected{% endif %}>Male</option>
                <option value="female" {% if gender == 'female' %}selected{% endif %}>Female</option>
            </select>
            <div class="invalid-feedback">
                Please this field is required.
            </div>
        </div>

        <div class="form-group my-3">
            <label for="other_names">Phone</label>
            <input class="form-control" placeholder="Phone" value="{{phone}}" type="text" name="phone" id="type"
                required>
            <div class="invalid-feedback">
                Please this field is required.
            </div>
        </div>

        <div class="form-group my-3">
            <label for="password">Password</label>
            <input class="form-control" placeholder="Password" type="password" name="password" id="password">
            <div class="invalid-feedback">
                Please this field is required.
            </div>
        </div>

        <div class="form-group my-3">
            <label for="password">Confirm Password</label>
            <input class="form-control" placeholder="Confirm Password" type="confirm_password" name="confirm_password"
                id="confirm_password">
            <div class="invalid-feedback">
                Please this field is required.
            </div>
        </div>

        <div class="form-group mt-5 mb-3">
            <label for="group_ids">Groups</label>
            <select class="form-control" name="group_ids" id="group_ids" multiple>
                {% for group in groups %}
                    <option value="{{group.id}}" {% if group in user.groups.all %}selected{% endif %}>{{group.name}}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="mt-4 form-group">
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
    </div>

</form>

app/accounts/templates/accounts/users/users.html
{% extends 'templates/dashboard/base_template.html' %}
{% block page_title %}Users{% endblock %}
{% block active-sidebar-item-id %}users{%endblock%}

{% block breadcrumb %}
<section class="breadcrumb">
    <a href="{% url 'dashboard:index' %}" class="">Home <i class="bi bi-chevron-right"></i></a>
    <a href="" class="active">Users</a>
</section>
{% endblock %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="userModal" tabindex="-1" aria-labelledby="userModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content px-4">
            <div class="modal-header">
                <h5 class="modal-title" id="userModalLabel">Add User</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            {% include 'accounts/users/form_user.html' %}
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- End of Modal -->


<h4 class="page-header"><i class='icon bx bx-group'></i> USERS</h4>
<section class="card">
    <div class="card-header d-flex justify-content-between">
        <h4>Users</h4>
        <div class="">
            {% if perms.setup.add_user %}
            <button class="d-flex btn btn-sm btn-primary my-1" data-bs-toggle="modal" data-bs-target="#userModal"><i
                    class="bi bi-plus"></i> Add
            </button>
            {% endif %}
        </div>
    </div>
    <div class="card-body">
        <div class="col-md-12" style="overflow-x: auto;">
            <table class="table data-table">
                <thead class="bg-primary text-light">
                    <tr>
                        <th>S/N</th>
                        <th>Username</th>
                        <th>Surname</th>
                        <th>Other Names</th>
                        <th>Phone</th>
                        <th>Groups</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{user.username}}</td>
                        <td>{{user.surname}}</td>
                        <td>{{user.other_names}}</td>
                        <td>{{user.phone}}</td>
                        <td>
                            {% for group in user.groups.all %}
                            <span class="badge bg-primary">{{group.name}}</span>
                            {% endfor %}
                        </td>
                        <td class="d-flex">
                            {% if perms.setup.change_user %}
                            <a href="{% url 'accounts:create_update_user' %}?id={{user.id}}"
                                class="me-3 d-flex btn btn-sm btn-light">
                                <i class="bi bi-pencil me-1"></i>
                                Edit
                            </a>
                            {% endif %}
                            {% if perms.setup.delete_user %}
                            <form action="{% url 'dashboard:delete_model' user.model_name user.id %}" method="POST"
                                class="requires-confirmation"
                                data-message="Click on okay to permanently delete '{{user.get_name}}'.">
                                {% csrf_token %}
                                <input type="hidden" name="user_id" value="{{user.id}}">
                                <button type="submit" class="btn btn-sm btn-light"><span class="d-flex">
                                        <i class="bi bi-trash"></i> Delete</span>
                                </button>
                            </form>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>

{% endblock %}