app/dashboard/urls.py
from django.urls import path

from . import views

# yapf: disable

app_name = "dashboard"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('delete/<str:model_name>/<str:instance_id>', views.DeleteModelView.as_view(), name='delete_model'),
    path('model_agnostic_image_upload/<str:model_name>/<str:model_id>/<str:field_name>', views.ModelAgnosticImageUploadView.as_view(), name='model_agnostic_image_upload'),
    path('crop-model-image/<str:model_name>/<str:model_id>/<str:field_name>', views.CropModelImageView.as_view(), name='crop_model_image'),
    path('tasks/<str:task_id>/stream-status', views.StreamTaskStatusView.as_view(), name='stream_task_status'),

    # Students
    path('students/', views.StudentsView.as_view(), name='students'),
    path('students/create-update', views.CreateUpdateStudentView.as_view(), name='create_update_student'),
    path('students/create-update-bulk', views.AddBulkStudents.as_view(), name='create_update_student_bulk'),

    # Subjects
    path('subjects/', views.SubjectsView.as_view(), name='subjects'),
    path('subjects/create-update', views.CreateUpdateSubjectView.as_view(), name="create_update_subject"),

    # Courses
    path('courses/', views.CoursesView.as_view(), name='courses'),
    path('courses/create-update', views.CreateUpdateCourseView.as_view(), name="create_update_course"),

    # Department
    path('departments/', views.DepartmentsView.as_view(), name='departments'),
    path('departments/create-update', views.CreateUpdateDepartmentView.as_view(), name="create_update_department"),

    # Staff
    path('staff/', views.StaffView.as_view(), name='staff'),
    path('staff/create-update', views.CreateUpdateStaffView.as_view(), name="create_update_staff"),

    # Staff
    path('classes/', views.ClassesView.as_view(), name='classes'),
    path('classes/create-update', views.CreateUpdateClassView.as_view(), name="create_update_class"),

    # House
    path('houses/', views.HousesView.as_view(), name='houses'),
    path('houses/create-update', views.CreateUpdateHouseView.as_view(), name="create_update_house"),

    # House
    path('tasks/', views.TasksView.as_view(), name='tasks'),
    path('tasks/create-update', views.CreateUpdateTaskView.as_view(), name="create_update_task"),
    path('tasks/task-send-notification', views.SendTaskNotification.as_view(), name="task_send_notification"),

    # Action Center
    path('action-center/', views.ActionCenterView.as_view(), name='action_center'),
    path('action-center/subject-mapping', views.SubjectMappingView.as_view(), name='subject_mapping'),
    path('action-center/reset-subject-mapping', views.ResetSubjectMappingView.as_view(), name='reset_subject_mapping'),
    path('action-center/student-promotion', views.StudentPromotionView.as_view(), name='student_promotion'),
    path('action-center/student-promotion-revert', views.RevertPromotionView.as_view(), name='student_promotion_revert'),
    path('action-center/academic-record-selection', views.AcademicRecordSelectionView.as_view(), name='academic_record_selection'),
    path('action-center/academic-record-data', views.AcademicRecordDataView.as_view(), name='academic_record_data'),
    path('action-center/reset-academic-record-data', views.ResetAcademicRecord.as_view(), name='reset_academic_record_data'),

    # Reporting
    path('reporting/index', views.ReportingIndexView.as_view(), name='reporting_index'),
    path('reporting/student-full-report', views.StudentFullReportView.as_view(), name='student_full_report'),
    path('reporting/generate-report-sheet', views.BulkAcademicRecordReportView.as_view(), name='gerate_bulk_student_report_sheet'),
    path('reporting/generate-report-sheet/<str:task_id>/<str:filename>/status', views.StudentReportGenerationStatusView.as_view(), name='bulk_report_sheet_generation_status'),

    # Class teacher reporting
    path('reporting/class-teacher-report-filter', views.ClassTeacherSessionReportFilterView.as_view(), name='class_teacher_report_filter'),
    path('reporting/class-teacher-report-data', views.ClassTeacherSessionReportDataView.as_view(), name='class_teacher_report_data'),

    # House master reporting
    path('reporting/house-master-report-filter', views.HouseMasterSessionReportFilterView.as_view(), name='house_master_report_filter'),
    path('reporting/house-master-report-data', views.HouseMasterSessionReportDataView.as_view(), name='house_master_report_data'),

    # House master reporting
    path('reporting/assistant-head-report-filter', views.AssistantHeadSessionReportFilterView.as_view(), name='assistant_head_report_filter'),
    path('reporting/assistant-head-report-data', views.AssistantHeadSessionReportDataView.as_view(), name='assistant_head_report_data'),

    # Notifications
    path('notifications/', views.NotificationIndexView.as_view(), name='notifications'),
    path('notifications/history', views.NotificationHistoryView.as_view(), name='notification_history'),
    path('notifications/compose-sms/', views.ComposeSMS.as_view(), name='compose_sms'),
    path('notifications/preview-sms/', views.PreviewSMS.as_view(), name='preview_sms'),
    path('notifications/send-pin-sms/', views.SendPINNotification.as_view(), name='send_pin_sms'),
    path('notifications/confirm-pin-notification/', views.ConfirmPINNotification.as_view(), name='confirm_pin_notification'),
    path('notifications/report-notifications/', views.SendReportNotification.as_view(), name='report_notifications'),
    path('notifications/bill-notifications/', views.SendBillNotification.as_view(), name='bill_notifications'),
    path('notifications/report-notification-confirmation/', views.ConfirmReportNotification.as_view(), name='report_notification_confirmation'),
    path('notifications/bill-notification-confirmation/', views.ConfirmBillNotification.as_view(), name='bill_notification_confirmation'),
]


urlpatterns += [
    path('accounting/', views.AccountingIndexView.as_view(), name='accounting'),
    path('accounting/invoices', views.InvoicesView.as_view(), name='invoices'),
    path('accounting/payments', views.PaymentsView.as_view(), name='payments'),
    path('accounting/create-update-payment/<str:student_id>/pay', views.CreateUpdatePayments.as_view(), name='create_update_payment'),
    path('accounting/create-update-invoice', views.CreateUpdateInvoiceView.as_view(), name='create_update_invoice'),
    path('accounting/invoice/<str:invoice_id>/create_update_invoice_item', views.CreateUpdateInvoiceItem.as_view(), name='create_update_invoice_item'),
    path('accounting/invoice/<str:invoice_id>/details', views.InvoiceDetailsView.as_view(), name='invoice_details'),
    
    path('accounting/generate-bill-sheet/<str:invoice_id>', views.BulkInvoiceGenerator.as_view(), name='gerate_bulk_student_bill_sheet'),
    path('accounting/generate-bill-sheet/<str:task_id>/<str:filename>/status', views.GeneralReportStatusView.as_view(), name='bulk_bill_sheet_generation_status'),
    
    path('accounting/student-invoices/<str:student_id>/', views.StudentInvoicesView.as_view(), name='student_invoices'),
    path('accounting/student-invoices/<str:student_id>/<str:invoice_id>', views.StudentInvoiceDetailView.as_view(), name='student_invoice_details'),
]

urlpatterns += [
    path('inventory/', views.InventoryIndexView.as_view(), name='inventory_index'),
    path('inventory/inventories', views.InventoriesView.as_view(), name='inventories'),
    path('inventory/inventories/create-update', views.CreateUpdateInventoryView.as_view(), name="create_update_inventory"),

    path('inventory/issuance', views.IssuanceView.as_view(), name='issuance'),
    path('inventory/issuance/create-update', views.CreateUpdateIssuanceView.as_view(), name="create_update_issuance"),
]

#Personal
urlpatterns += [
    path('personal/academic-record', views.PesonalAcademicRecord.as_view(), name='personal_academic_record'),
    path('personal/my-invoices', views.MyInvoicesView.as_view(), name='my_invoices'),
    path('personal/my-invoices/<str:invoice_id>/detail', views.MyInvoiceDetailView.as_view(), name='my_invoice_detail'),
    path('personal/payment-history', views.PersonalPaymentHistory.as_view(), name='payment_history'),
]

# User profile
urlpatterns += [
    path('user-profile', views.UserProfileIndexView.as_view(), name='user_profile'),
    path('user-profile/photo', views.UserProfilePhotoView.as_view(), name='user_profile_profile'),
]

app/lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('app/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('setup/', include('setup.urls')),
    path('pdf/', include('pdf_processor.urls')),
    path('api/v1/', include('graphql_api.urls')),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

# Customize django admin page.
admin.site.site_header = "LMS SYSTEM ADMINISTRATION"  # default: "Django Administration"
admin.site.index_title = "Site Administration"  # default: "Site Administration"
admin.site.site_title = 'LMS System site admin'  # default: "Django site admin"

app/website/urls.py
from django.urls import include, path
from . import views

app_name = "website"
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('about', views.AboutView.as_view(), name="about"),
    path('contact', views.ContactView.as_view(), name="contact"),
    path('enrollment', views.EnrollmentView.as_view(), name="enrollment"),
]

app/website/views.py
from django.shortcuts import render
from django.views import View


class IndexView(View):
    template_name = "website/index.html"

    def get(self, request):
        return render(request, self.template_name)


class AboutView(View):
    template_name = "website/about_us.html"

    def get(self, request):
        return render(request, self.template_name)


class ContactView(View):
    template_name = "website/contact.html"

    def get(self, request):
        return render(request, self.template_name)


class EnrollmentView(View):
    template_name = "website/enrollment.html"

    def get(self, request):
        return render(request, self.template_name)

app/website/templates/website/about_us.html
{% extends 'templates/website/base_template.html' %}
{% block page_title %}About Us{% endblock %}
{% load static %}

{% block content %}
<div class="page-banner d-flex align-items-center justify-content-center"
style="background-image: url({% static 'images/sports.jpeg' %})">
    <div>
        <h1 class="text-center text-light">About Us</h1>
    </div>
</div>

<div class="my-5 p-3">
    <h1 class="text-center text-primary" style="font-weight: 900;">Mission</h1>
    <p class="col-md-6 text-muted my-4 mx-auto" style="text-align: justify;">
        At Global Evangelical Basic School, we are committed to empowering our students to become their best selves. Our mission is to provide them with the essential resources and skills they need to reach their full academic potential and become active, engaged members of their communities. We believe that by fostering a love of learning and a sense of social responsibility, we can help shape the leaders of tomorrow and create a brighter future for all.
    </p>
</div>

<div class="my-5 p-3">
    <h1 class="text-center text-primary" style="font-weight: 900;">Vision</h1>
    <p class="col-md-6 text-muted my-4 mx-auto" style="text-align: justify;">
        Global Evangelical Basic School envisions a world where every child has access to excellent education, and we strive to inspire our students to become lifelong learners and agents of positive change in their communities and beyond.
    </p>
</div>


<div class="my-5 p-3">
    <h1 class="text-center text-primary" style="font-weight: 900;">Core Values</h1>
    <div class="row col-md-6 mx-auto">
        <div class="col-md-6 my-3">
            <h6 class="text-primary"><strong>Empowerment</strong></h6>
            <p style="text-align: justify;">We empower our students to reach their full potential and become active, engaged members of their communities.</p>
        </div>
        
        <div class="col-md-6 my-3">
            <h6 class="text-primary"><strong>Excellence</strong></h6>
            <p style="text-align: justify;">We are committed to excellence in all aspects of education, from innovative teaching methods to student achievement.</p>
        </div>
            
        <div class="col-md-6 my-3">
            <h6 class="text-primary"><strong>Social responsibility</strong></h6>
            <p style="text-align: justify;">We instill in our students a sense of social responsibility and encourage them to become agents of positive change in their communities and beyond.</p>
        </div>
            
        <div class="col-md-6 my-3">
            <h6 class="text-primary"><strong>Lifelong learning</strong></h6>
            <p style="text-align: justify;">We value lifelong learning and strive to inspire our students to become lifelong learners themselves.</p>
        </div>
            
        <div class="col-md-6 my-3">
            <h6 class="text-primary"><strong>Equity</strong></h6>
            <p style="text-align: justify;">We believe that every child has the right to excellent education and equal opportunities to succeed, and we work to create an equitable and inclusive learning environment for all.</p>
        </div>
    </div>
</div>


{% endblock %}

app/website/templates/website/base_template.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="GLOBAL EVANGELICAL BASIC SCHOOL">
    <meta name="author" content="GLOBAL EVANGELICAL BASIC SCHOOL">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{{request.school.logo_url}}" type="image/png">

    <title>{% block page_title %}Home{% endblock %} | GLOBAL EVANGELICAL BASIC SCHOOL</title>
</head>
<body>
    
    <div class="top-bar"></div>
    <nav class="top-nav d-flex d-flex align-items-center justify-content-center">
        <div class="nav-container d-flex align-items-center">
            <div class="logo me-5">
                {% if request.school.logo %}
                    <img src="{{request.school.logo.url}}" alt="UG Logo" height="50">
                    {% else %}
                    <img src="{% static 'images/logo.png' %}" alt="UG Logo" height="50">
                    {% endif %}
            </div>
            <div class="menu mx-5 d-none d-md-flex">
                <a href="{% url 'website:index' %}" class="menu-item mx-2">HOME</a>
                <a href="{% url 'website:about' %}" class="menu-item mx-2">ABOUT</a>
                <a href="{% url 'website:enrollment' %}" class="menu-item mx-2">ENROLL</a>
                <a href="{% url 'website:contact' %}" class="menu-item mx-2">CONTACT</a>
            </div>
            <a href="{% url 'dashboard:index' %}" class="btn btn-sm px-3 btn-primary ms-5">Portal</a>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
    
    <footer class="mt-5">
        <hr>
        <div class="col-md-6 mx-auto my-2">
            <h6 class="text-muted">Navigations</h6>
            <p class="m-0"><a href="{% url 'website:index' %}" class="text-muted menu-item mx-2">Home</a></p>
            <p class="m-0"><a href="{% url 'website:about' %}" class="text-muted menu-item mx-2">About</a></p>
            <p class="m-0"><a href="{% url 'website:enrollment' %}" class="text-muted menu-item mx-2">Enroll</a></p>
            <p class="m-0"><a href="{% url 'website:contact' %}" class="text-muted menu-item mx-2">Contact</a></p>
        </div>
        <p class="text-center my-3">All rights reserved. &copy; 2023 </p>
    </footer>
</body>

</html>

app/website/templates/website/contact.html
{% extends 'templates/website/base_template.html' %}
{% block page_title %}Contact{% endblock %}
{% load static %}

{% block content %}
<div class="page-banner d-flex align-items-center justify-content-center"
style="background-image: url({% static 'images/sports.jpeg' %})">
    <div>
        <h1 class="text-center text-light">Contact</h1>
    </div>
</div>

<div class="my-5 p-3">
    <h1 class="text-center text-primary" style="font-weight: 900;">Contact</h1>
    <div class="row col-md-6 mx-auto">
        <p class="m-0 text-center">Global Evangelical School</p>
        <p class="m-0 text-center">Tettekope</p>
        <p class="m-0 text-center">P.O Box 182, Keta</p>
    </div>
</div>


{% endblock %}

app/website/templates/website/enrollment.html
{% extends 'templates/website/base_template.html' %}
{% block page_title %}Enrol{% endblock %}
{% load static %}

{% block content %}
<div class="page-banner d-flex align-items-center justify-content-center"
style="background-image: url({% static 'images/sports.jpeg' %})">
    <div>
        <h1 class="text-center text-light">Enrollment</h1>
    </div>
</div>

<div class="my-5 p-3">
    <h1 class="text-center text-primary" style="font-weight: 900;">Enrollment</h1>
    <div class="row col-md-6 mx-auto">
       <p class="text-center">Please visit our campus at Global Evangelical School - Tettekope, Keta</p>
    </div>
</div>
{% endblock %}

app/website/templates/website/index.html
{% extends 'templates/website/base_template.html' %}
{% block page_title %}GLOBAL EVANGELICAL BASIC SCHOOL{% endblock %}
{% load static %}

{% block content %}
<div class="page-banner d-flex align-items-center justify-content-center"
style="background-image: url({% static 'images/home-page-banner.jpeg' %})">
<div>
    <h1 class="text-center text-light">Quality Education</h1>
    <h5 class="text-center text-light">FROM US TO YOU</h5>
    <p class="text-center mt-5 bubble"><a href="{% url 'website:enrollment' %}" class="btn btn-primary p-3"><strong>Enroll now</strong></a></p>
</div>
</div>

<br>
<br>
<br>
<br>
<br>
<div class="my-5">
<h2 class="text-center">Welcome to</h2>
<h1 class="text-center text-primary" style="font-weight: 900;"><strong>Global Evangelical Basic School</strong></h1>
<h1 class="text-center text-primary">Tettekope, Keta</h1>
<div class="d-flex justify-content-center">
    <span style="height: 0.2em; width: 8em;" class="bg-primary"></span>
</div>
<p class="col-md-6 text-muted my-4 mx-auto text-center">
    The objective of the Global Evangelical Basic School is to equip our children with the necessary tools to reach their full potential, both academically and as active participants in their communities.
</p>
</div>


<br>
<br>
<br>
<br>
<br>

{% endblock %}