app/dashboard/urls.py
from django.urls import path

from . import views

# yapf: disable

app_name = "dashboard"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('delete/<str:model_name>/<str:instance_id>', views.DeleteModelView.as_view(), name='delete_model'),
    path('model_agnostic_image_upload/<str:model_name>/<str:model_id>/<str:field_name>', views.ModelAgnosticImageUploadView.as_view(), name='model_agnostic_image_upload'),
    path('crop-model-image/<str:model_name>/<str:model_id>/<str:field_name>', views.CropModelImageView.as_view(), name='crop_model_image'),
    path('tasks/<str:task_id>/stream-status', views.StreamTaskStatusView.as_view(), name='stream_task_status'),

    # Students
    path('students/', views.StudentsView.as_view(), name='students'),
    path('students/create-update', views.CreateUpdateStudentView.as_view(), name='create_update_student'),
    path('students/create-update-bulk', views.AddBulkStudents.as_view(), name='create_update_student_bulk'),

    # Subjects
    path('subjects/', views.SubjectsView.as_view(), name='subjects'),
    path('subjects/create-update', views.CreateUpdateSubjectView.as_view(), name="create_update_subject"),

    # Courses
    path('courses/', views.CoursesView.as_view(), name='courses'),
    path('courses/create-update', views.CreateUpdateCourseView.as_view(), name="create_update_course"),

    # Department
    path('departments/', views.DepartmentsView.as_view(), name='departments'),
    path('departments/create-update', views.CreateUpdateDepartmentView.as_view(), name="create_update_department"),

    # Staff
    path('staff/', views.StaffView.as_view(), name='staff'),
    path('staff/create-update', views.CreateUpdateStaffView.as_view(), name="create_update_staff"),

    # Staff
    path('classes/', views.ClassesView.as_view(), name='classes'),
    path('classes/create-update', views.CreateUpdateClassView.as_view(), name="create_update_class"),

    # House
    path('houses/', views.HousesView.as_view(), name='houses'),
    path('houses/create-update', views.CreateUpdateHouseView.as_view(), name="create_update_house"),

    # House
    path('tasks/', views.TasksView.as_view(), name='tasks'),
    path('tasks/create-update', views.CreateUpdateTaskView.as_view(), name="create_update_task"),
    path('tasks/task-send-notification', views.SendTaskNotification.as_view(), name="task_send_notification"),

    # Action Center
    path('action-center/', views.ActionCenterView.as_view(), name='action_center'),
    path('action-center/subject-mapping', views.SubjectMappingView.as_view(), name='subject_mapping'),
    path('action-center/reset-subject-mapping', views.ResetSubjectMappingView.as_view(), name='reset_subject_mapping'),
    path('action-center/student-promotion', views.StudentPromotionView.as_view(), name='student_promotion'),
    path('action-center/student-promotion-revert', views.RevertPromotionView.as_view(), name='student_promotion_revert'),
    path('action-center/academic-record-selection', views.AcademicRecordSelectionView.as_view(), name='academic_record_selection'),
    path('action-center/academic-record-data', views.AcademicRecordDataView.as_view(), name='academic_record_data'),
    path('action-center/reset-academic-record-data', views.ResetAcademicRecord.as_view(), name='reset_academic_record_data'),

    # Reporting
    path('reporting/index', views.ReportingIndexView.as_view(), name='reporting_index'),
    path('reporting/student-full-report', views.StudentFullReportView.as_view(), name='student_full_report'),
    path('reporting/generate-report-sheet', views.BulkAcademicRecordReportView.as_view(), name='gerate_bulk_student_report_sheet'),
    path('reporting/generate-report-sheet/<str:task_id>/<str:filename>/status', views.StudentReportGenerationStatusView.as_view(), name='bulk_report_sheet_generation_status'),

    # Class teacher reporting
    path('reporting/class-teacher-report-filter', views.ClassTeacherSessionReportFilterView.as_view(), name='class_teacher_report_filter'),
    path('reporting/class-teacher-report-data', views.ClassTeacherSessionReportDataView.as_view(), name='class_teacher_report_data'),

    # House master reporting
    path('reporting/house-master-report-filter', views.HouseMasterSessionReportFilterView.as_view(), name='house_master_report_filter'),
    path('reporting/house-master-report-data', views.HouseMasterSessionReportDataView.as_view(), name='house_master_report_data'),

    # House master reporting
    path('reporting/assistant-head-report-filter', views.AssistantHeadSessionReportFilterView.as_view(), name='assistant_head_report_filter'),
    path('reporting/assistant-head-report-data', views.AssistantHeadSessionReportDataView.as_view(), name='assistant_head_report_data'),

    # Notifications
    path('notifications/', views.NotificationIndexView.as_view(), name='notifications'),
    path('notifications/history', views.NotificationHistoryView.as_view(), name='notification_history'),
    path('notifications/compose-sms/', views.ComposeSMS.as_view(), name='compose_sms'),
    path('notifications/preview-sms/', views.PreviewSMS.as_view(), name='preview_sms'),
    path('notifications/send-pin-sms/', views.SendPINNotification.as_view(), name='send_pin_sms'),
    path('notifications/confirm-pin-notification/', views.ConfirmPINNotification.as_view(), name='confirm_pin_notification'),
    path('notifications/report-notifications/', views.SendReportNotification.as_view(), name='report_notifications'),
    path('notifications/bill-notifications/', views.SendBillNotification.as_view(), name='bill_notifications'),
    path('notifications/report-notification-confirmation/', views.ConfirmReportNotification.as_view(), name='report_notification_confirmation'),
    path('notifications/bill-notification-confirmation/', views.ConfirmBillNotification.as_view(), name='bill_notification_confirmation'),
]


urlpatterns += [
    path('accounting/', views.AccountingIndexView.as_view(), name='accounting'),
    path('accounting/invoices', views.InvoicesView.as_view(), name='invoices'),
    path('accounting/payments', views.PaymentsView.as_view(), name='payments'),
    path('accounting/create-update-payment/<str:student_id>/pay', views.CreateUpdatePayments.as_view(), name='create_update_payment'),
    path('accounting/create-update-invoice', views.CreateUpdateInvoiceView.as_view(), name='create_update_invoice'),
    path('accounting/invoice/<str:invoice_id>/create_update_invoice_item', views.CreateUpdateInvoiceItem.as_view(), name='create_update_invoice_item'),
    path('accounting/invoice/<str:invoice_id>/details', views.InvoiceDetailsView.as_view(), name='invoice_details'),
    
    path('accounting/generate-bill-sheet/<str:invoice_id>', views.BulkInvoiceGenerator.as_view(), name='gerate_bulk_student_bill_sheet'),
    path('accounting/generate-bill-sheet/<str:task_id>/<str:filename>/status', views.GeneralReportStatusView.as_view(), name='bulk_bill_sheet_generation_status'),
    
    path('accounting/student-invoices/<str:student_id>/', views.StudentInvoicesView.as_view(), name='student_invoices'),
    path('accounting/student-invoices/<str:student_id>/<str:invoice_id>', views.StudentInvoiceDetailView.as_view(), name='student_invoice_details'),
]

urlpatterns += [
    path('inventory/', views.InventoryIndexView.as_view(), name='inventory_index'),
    path('inventory/inventories', views.InventoriesView.as_view(), name='inventories'),
    path('inventory/inventories/create-update', views.CreateUpdateInventoryView.as_view(), name="create_update_inventory"),

    path('inventory/issuance', views.IssuanceView.as_view(), name='issuance'),
    path('inventory/issuance/create-update', views.CreateUpdateIssuanceView.as_view(), name="create_update_issuance"),
]

#Personal
urlpatterns += [
    path('personal/academic-record', views.PesonalAcademicRecord.as_view(), name='personal_academic_record'),
    path('personal/my-invoices', views.MyInvoicesView.as_view(), name='my_invoices'),
    path('personal/my-invoices/<str:invoice_id>/detail', views.MyInvoiceDetailView.as_view(), name='my_invoice_detail'),
    path('personal/payment-history', views.PersonalPaymentHistory.as_view(), name='payment_history'),
]

# User profile
urlpatterns += [
    path('user-profile', views.UserProfileIndexView.as_view(), name='user_profile'),
    path('user-profile/photo', views.UserProfilePhotoView.as_view(), name='user_profile_profile'),
]

app/lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('app/', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('setup/', include('setup.urls')),
    path('pdf/', include('pdf_processor.urls')),
    path('api/v1/', include('graphql_api.urls')),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

# Customize django admin page.
admin.site.site_header = "LMS SYSTEM ADMINISTRATION"  # default: "Django Administration"
admin.site.index_title = "Site Administration"  # default: "Site Administration"
admin.site.site_title = 'LMS System site admin'  # default: "Django site admin"

app/dashboard/models/utils.py
from django.db.models import Manager, QuerySet
from django.db import models


class AppQuerySet(QuerySet):
    def delete(self, hard=False):
        self.update(deleted=True)
        if hard:
            super().delete()


class AppManager(Manager):
    def get_queryset(self):
        return AppQuerySet(self.model, using=self._db) #.exclude(deleted=True)


class BaseModel(models.Model):
    class Meta:
        abstract = True
        # unique_together = ['id', 'deleted']

    id = models.AutoField(primary_key=True, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)

    def model_name(self):
        return self.__class__.__name__.lower()

    objects = AppManager()

    def delete(self, hard=False):
        self.deleted = True
        self.save()
        if hard:
            super().delete()

app/dashboard/views/assistant_head_report.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views import View

from dashboard.models import SessionReport, StudentPromotionHistory
from setup.models import SchoolSession


class AssistantHeadSessionReportFilterView(PermissionRequiredMixin, View):
    template_name = "dashboard/assistant_head_report/report_filter.html"
    permission_required = [
        "setup.append_signature",
    ]

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        sessions = SchoolSession.objects.all().order_by("-start_date")

        context = {
            "sessions": sessions,
        }
        return render(request, self.template_name, context)


class AssistantHeadSessionReportDataView(PermissionRequiredMixin, View):
    template_name = "dashboard/assistant_head_report/assistant_head_report_data.html"
    permission_required = [
        "setup.append_signature",
    ]

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        session_id = request.GET.get("session") or -1
        session = SchoolSession.objects.filter(id=session_id).first()

        if not session:
            messages.error(request, "Session not found")
            return redirect("dashboard:assistant_head_report_filter")

        promotion_history = StudentPromotionHistory.objects.filter(
            session__academic_year=session.academic_year)
        students = promotion_history.values_list("student", flat=True)

        for student_id in students:
            try:
                SessionReport.objects.get_or_create(student_id=student_id,
                                                    deleted=False,
                                                    session=session)
            except Exception as _:
                SessionReport.objects.filter(student_id=student_id,
                                             deleted=False,
                                             session=session).delete()

        reports = SessionReport.objects.filter(student__in=students,
                                               deleted=False,
                                               student__completed=False,
                                               session=session).order_by("klass", "student__user__surname")
        context = {
            "reports": reports,
            "session": session,
        }
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="accounts:login"))
    def post(self, request):
        session_id = request.GET.get("session") or -1
        session = SchoolSession.objects.filter(id=session_id).first()

        if not session:
            messages.error(request, "Session not found")
            return redirect("dashboard:assistant_head_report_filter")

        promotion_history = StudentPromotionHistory.objects.filter(
            session__academic_year=session.academic_year)
        students = promotion_history.values_list("student", flat=True)

        for student_id in students:
            SessionReport.objects.get_or_create(student_id=student_id,
                                                deleted=False,
                                                session=session)

        reports = SessionReport.objects.filter(student__in=students,
                                               deleted=False,
                                               session=session)
        for report in reports:
            report.assistant_head_signature = request.user.signature
            report.save()

        messages.success(request, "Record successfully signed.")
        return redirect(request.META.get("HTTP_REFERER"))

app/dashboard/views/classes.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View

from dashboard.forms import ClassForm
from dashboard.mixins import CreateUpdateMixin
from dashboard.models import Course, Klass, Staff


class ClassesView(PermissionRequiredMixin, View):
    template_name = "dashboard/classes/classes.html"
    permission_required = [
        "setup.view_class",
    ]

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        classes = Klass.objects.filter(deleted=False)
        courses = Course.objects.filter(deleted=False)
        staff = Staff.objects.filter(user__is_active=True, has_left=False)
        context = {
            "classes": classes,
            "staff": staff,
            "courses": courses,
        }
        return render(request, self.template_name, context)


class CreateUpdateClassView(PermissionRequiredMixin, CreateUpdateMixin):
    template_name = "dashboard/classes/edit_class.html"
    form_class = ClassForm
    object_id_field = "id"
    model_class = Klass
    object_name = "class"
    redirect_url = "dashboard:classes"
    permission_required = (
        "setup.add_class",
        "setup.change_class",
    )

    def get_context_data(self):
        return {
            "staff": Staff.objects.filter(user__is_active=True,
                                          has_left=False),
            "courses": Course.objects.all(),
        }

app/dashboard/views/courses.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View

from dashboard.forms import CourseForm
from dashboard.mixins import CreateUpdateMixin
from dashboard.models import Course, Department, Subject


class CoursesView(PermissionRequiredMixin, View):
    template_name = "dashboard/courses/courses.html"
    permission_required = [
        "dashboard.view_course",
    ]

    @method_decorator(login_required(login_url="accounts:login"))
    def get(self, request):
        courses = Course.objects.filter(deleted=False)
        subjects = Subject.objects.filter(deleted=False)
        departments = Department.objects.filter(deleted=False)
        context = {
            "courses": courses,
            "departments": departments,
            "subjects": subjects,
        }
        return render(request, self.template_name, context)


class CreateUpdateCourseView(PermissionRequiredMixin, CreateUpdateMixin):
    template_name = "dashboard/courses/edit_course.html"
    form_class = CourseForm
    object_id_field = "course_id"
    model_class = Course
    object_name = "course"
    redirect_url = "dashboard:courses"
    permission_required = (
        "dashboard.add_course",
        "dashboard.change_course",
    )

    def get_context_data(self):
        departments = Department.objects.filter(deleted=False)
        subjects = Subject.objects.filter(deleted=False)
        return {
            "subjects": subjects,
            "departments": departments,
        }

app/dashboard/templates/dashboard/courses/courses.html
{% extends 'templates/dashboard/base_template.html' %}
{% block page_title %}Courses{% endblock %}
{% block active-sidebar-item-id %}courses{%endblock%}

{% block breadcrumb %}
<section class="breadcrumb">
    <a href="{% url 'dashboard:index' %}" class="">Home <i class="bi bi-chevron-right"></i></a>
    <a href="" class="active">Courses</a>
</section>
{% endblock %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="courseModal" tabindex="-1" aria-labelledby="courseModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-l">
        <div class="modal-content px-4">
            <div class="modal-header">
                <h5 class="modal-title" id="courseModalLabel">Add Courses</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            {% include 'dashboard/courses/form_course.html' %}
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- End of Modal -->

<h4 class="page-header"><i class='icon bx bx-group'></i> COURSES</h4>
<section class="card">
    <div class="card-header d-flex justify-content-between">
        <h4>Courses</h4>
        <div class="">
            {% if perms.setup.add_course %}
            <button class="d-flex btn btn-sm btn-primary my-1" data-bs-toggle="modal" data-bs-target="#courseModal"><i
                    class="bi bi-plus"></i> Add
            </button>
            {% endif %}
        </div>
    </div>
    <div class="card-body">
        <div class="" style="overflow-x: auto;">
            <table class="table data-table">
                <thead class="bg-primary text-light">
                    <tr>
                        <th>S/N</th>
                        <th>CODE</th>
                        <th>NAME</th>
                        <th>SUBJECTS</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for course in courses %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{course.code}}</td>
                        <td>{{course.name}}</td>
                        <td>
                            {% for elective in course.subjects.all %}
                            <span class="badge bg-primary">{{elective.code|upper}}</span>
                            {% endfor %}
                        </td>
                        <td class="d-flex">
                            {% if perms.setup.change_course %}
                            <a href="{% url 'dashboard:create_update_course' %}?course_id={{course.id}}"
                                class="me-3 d-flex btn btn-sm btn-light">
                                <i class="bi bi-pencil me-1"></i>
                                Edit
                            </a>
                            {% endif %}
                            {% if perms.setup.delete_course %}
                            <form action="{% url 'dashboard:delete_model' course.model_name course.id %}" method="POST"
                                class="requires-confirmation"
                                data-message="Click on okay to permanently delete {{course.name}}">
                                {% csrf_token %}
                                <input type="hidden" name="course_id" value="{{course.id}}">
                                <button type="submit" class="btn btn-sm btn-light"><span class="d-flex">
                                        <i class="bi bi-trash"></i> Delete</span>
                                </button>
                            </form>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>

{% endblock %}

app/dashboard/templates/dashboard/courses/edit_course.html
{% extends 'templates/dashboard/base_template.html' %}
{% block page_title %}Courses{% endblock %}
{% block active-sidebar-item-id %}courses{%endblock%}

{% block breadcrumb %}
<section class="breadcrumb">
    <a href="{% url 'dashboard:index' %}" class="">Home <i class="bi bi-chevron-right"></i></a>
    <a href="{% url 'dashboard:courses' %}">Courses <i class="bi bi-chevron-right"></i></a>
    <a class="active">{{course.name|title}}</a>
</section>
{% endblock %}

{% block content %}

<div class="row col-md-11 mx-auto">
    <section class="col-md-6 mx-auto">
        <div class="card p-4">
            <div class="d-flex justify-content-between">
                <h6>COURSES</h6>
            </div>
            {% include 'dashboard/courses/form_course.html' %}
        </div>
    </section>
</div>
{% endblock %}

app/dashboard/templates/dashboard/courses/form_course.html
<form action="{% url 'dashboard:create_update_course' %}" class="needs-validation my-4" method="POST" novalidate>
    {% csrf_token %}
    <input type="hidden" name="course_id" value="{{course.id}}">
    <div class="form-group">
        <label for="name">Code</label>
        <input class="form-control" placeholder="E.g., BUS" value="{{code}}" type="text" name="code" id="code" required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>
    <div class="form-group mt-4">
        <label for="name">Name</label>
        <input class="form-control" placeholder="Name e.g, Business" value="{{name}}" type="text" name="name" id="name"
            required>
        <div class="invalid-feedback">
            Please this field is required.
        </div>
    </div>

    <div class="mt-4 form-group">
        <p>All Subjects</p>
        {% for subject in subjects|dictsort:"name" %}
        <div class="form-check">
            <label for="filed_subject_{{subject.id}}">{{subject.name}} ({{subject.code}})</label>
            <input class="form-check-input" type="checkbox" value="{{subject.id}}" name="subjects"
                id="filed_subject_{{subject.id}}"
                {% if subject in course.subjects.all or subject.id in subjects %}checked{% endif %}>
        </div>
        {% endfor %}

        <a href="{% url 'dashboard:subjects' %}" target="_blank" class="mt-2 text-end d-block text-primary"><i
                class="bi bi-plus"></i> New subject</a>
    </div>
    
    <div class="mt-4 form-group">
        <p>Departments</p>
        {% for department in departments|dictsort:"name" %}
        <div class="form-check">
            <label for="filed_department_{{department.id}}">{{department.name}}</label>
            <input class="form-check-input" type="checkbox" value="{{department.id}}" name="departments"
                id="filed_department_{{department.id}}"
                {% if department in course.departments.all or department.id in departments %}checked{% endif %}>
        </div>
        {% endfor %}
        <a href="{% url 'dashboard:departments' %}" target="_blank" class="mt-2 text-end d-block text-primary"><i
                class="bi bi-plus"></i> New department</a>
    </div>


    <div class="mt-4 form-group">
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
    </div>

</form>